name: Publish package to the Maven Central Repository
on: [push]
jobs:
  publish:
    strategy:
      matrix:
        java: [8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Publish package
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.REPOSITORY_USER }}
          MAVEN_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}